export const BUILT_IN_PLANT_FAMILIES = [
  {
    id: 'nightshade',
    commonName: 'Nightshade',
    scientificName: 'Solanaceae',
    notes: 'Includes tomatoes, peppers, eggplants, and potatoes. Rotate to reduce shared pest and disease pressure.',
  },
  {
    id: 'cucurbit',
    commonName: 'Cucurbit',
    scientificName: 'Cucurbitaceae',
    notes: 'Includes cucumbers, squash, and pumpkins. Often sprawling crops with similar beetle and mildew pressure.',
  },
  {
    id: 'brassica',
    commonName: 'Brassica',
    scientificName: 'Brassicaceae',
    notes: 'Includes broccoli, cabbage, kale, and radish. Shares common cabbage worm and flea beetle issues.',
  },
  {
    id: 'legume',
    commonName: 'Legume',
    scientificName: 'Fabaceae',
    notes: 'Includes peas and beans. Generally nitrogen-fixing crops that are useful in rotation planning.',
  },
  {
    id: 'allium',
    commonName: 'Allium',
    scientificName: 'Amaryllidaceae',
    notes: 'Includes onions and garlic. Distinct aroma and nutrient patterns make them useful rotation breaks.',
  },
  {
    id: 'carrot_family',
    commonName: 'Carrot Family',
    scientificName: 'Apiaceae',
    notes: 'Includes carrots plus herbs like cilantro and dill. Watch for similar foliar and root pests.',
  },
  {
    id: 'grass',
    commonName: 'Grass',
    scientificName: 'Poaceae',
    notes: 'Includes corn and grain crops. Useful as a distinct category in larger rotation plans.',
  },
  {
    id: 'goosefoot',
    commonName: 'Goosefoot',
    scientificName: 'Amaranthaceae',
    notes: 'Includes beets and spinach. Often cool-season crops with moderate heat sensitivity.',
  },
  {
    id: 'aster',
    commonName: 'Aster',
    scientificName: 'Asteraceae',
    notes: 'Includes lettuce and many flowers such as marigolds. Useful for succession planning and companion zones.',
  },
  {
    id: 'mint',
    commonName: 'Mint',
    scientificName: 'Lamiaceae',
    notes: 'Includes basil and many culinary herbs. Often aromatic companion plants with softer spacing needs.',
  },
]

const FAMILY_BY_ID = BUILT_IN_PLANT_FAMILIES.reduce((families, family) => {
  families[family.id] = family
  return families
}, {})

function buildPlant(plant) {
  const family = FAMILY_BY_ID[plant.familyId] ?? null

  return {
    ...plant,
    name: plant.commonName,
    familyCommonName: family?.commonName ?? '',
    familyScientificName: family?.scientificName ?? '',
    sowBeforeLastFrostWeeks: plant.indoorStartWeeksBeforeLastFrost,
    directSowAfterLastFrostWeeks: plant.directSowWeeksRelativeToLastFrost,
    transplantAfterLastFrostWeeks: plant.transplantWeeksRelativeToLastFrost,
  }
}

export const BUILT_IN_PLANTS = [
  buildPlant({
    id: 'tomato',
    commonName: 'Tomato',
    scientificName: 'Solanum lycopersicum',
    familyId: 'nightshade',
    cropCategory: 'Fruiting',
    lifecycle: 'annual',
    frostSensitivity: 'tender',
    heatSensitivity: 'moderate',
    supportNeeds: 'cage',
    spacingInches: 24,
    rowSpacingInches: 36,
    daysToMaturityMin: 70,
    daysToMaturityMax: 90,
    indoorStartWeeksBeforeLastFrost: 6,
    directSowWeeksRelativeToLastFrost: null,
    transplantWeeksRelativeToLastFrost: 1,
    transplantMinNightTempF: 50,
    notes: 'Warm-season crop that benefits from support, airflow, and consistent watering.',
    defaultPlanningMethod: 'indoor_start',
    edgeClearanceInches: 6,
    color: '#d94b3d',
    shortLabel: 'Tm',
    symbol: 'ring',
  }),
  buildPlant({
    id: 'pepper',
    commonName: 'Pepper',
    scientificName: 'Capsicum annuum',
    familyId: 'nightshade',
    cropCategory: 'Fruiting',
    lifecycle: 'annual',
    frostSensitivity: 'tender',
    heatSensitivity: 'moderate',
    supportNeeds: 'stake',
    spacingInches: 18,
    rowSpacingInches: 24,
    daysToMaturityMin: 70,
    daysToMaturityMax: 90,
    indoorStartWeeksBeforeLastFrost: 8,
    directSowWeeksRelativeToLastFrost: null,
    transplantWeeksRelativeToLastFrost: 2,
    transplantMinNightTempF: 55,
    notes: 'Slow starter that prefers warm soil and consistently warm night temperatures.',
    defaultPlanningMethod: 'indoor_start',
    edgeClearanceInches: 6,
    color: '#f08a24',
    shortLabel: 'Pp',
    symbol: 'diamond',
  }),
  buildPlant({
    id: 'eggplant',
    commonName: 'Eggplant',
    scientificName: 'Solanum melongena',
    familyId: 'nightshade',
    cropCategory: 'Fruiting',
    lifecycle: 'annual',
    frostSensitivity: 'tender',
    heatSensitivity: 'moderate',
    supportNeeds: 'stake',
    spacingInches: 24,
    rowSpacingInches: 30,
    daysToMaturityMin: 70,
    daysToMaturityMax: 85,
    indoorStartWeeksBeforeLastFrost: 8,
    directSowWeeksRelativeToLastFrost: null,
    transplantWeeksRelativeToLastFrost: 2,
    transplantMinNightTempF: 55,
    notes: 'Prefers sustained warmth and benefits from sturdy support once fruit sets.',
    defaultPlanningMethod: 'indoor_start',
    edgeClearanceInches: 6,
    color: '#7b4fb3',
    shortLabel: 'Eg',
    symbol: 'diamond',
  }),
  buildPlant({
    id: 'potato',
    commonName: 'Potato',
    scientificName: 'Solanum tuberosum',
    familyId: 'nightshade',
    cropCategory: 'Tuber',
    lifecycle: 'annual',
    frostSensitivity: 'semi_hardy',
    heatSensitivity: 'moderate',
    supportNeeds: 'none',
    spacingInches: 12,
    rowSpacingInches: 30,
    daysToMaturityMin: 80,
    daysToMaturityMax: 120,
    indoorStartWeeksBeforeLastFrost: null,
    directSowWeeksRelativeToLastFrost: -2,
    transplantWeeksRelativeToLastFrost: null,
    transplantMinNightTempF: null,
    notes: 'Usually planted as seed potatoes directly in the bed before warm-season crops begin.',
    defaultPlanningMethod: 'direct_sow',
    edgeClearanceInches: 6,
    color: '#b5966d',
    shortLabel: 'Pt',
    symbol: 'root',
  }),
  buildPlant({
    id: 'cucumber',
    commonName: 'Cucumber',
    scientificName: 'Cucumis sativus',
    familyId: 'cucurbit',
    cropCategory: 'Fruiting',
    lifecycle: 'annual',
    frostSensitivity: 'tender',
    heatSensitivity: 'moderate',
    supportNeeds: 'trellis',
    spacingInches: 12,
    rowSpacingInches: 36,
    daysToMaturityMin: 50,
    daysToMaturityMax: 70,
    indoorStartWeeksBeforeLastFrost: 3,
    directSowWeeksRelativeToLastFrost: 1,
    transplantWeeksRelativeToLastFrost: 2,
    transplantMinNightTempF: 55,
    notes: 'Can be direct sown or transplanted. Trellising improves airflow and harvest visibility.',
    defaultPlanningMethod: 'direct_sow',
    edgeClearanceInches: 4,
    color: '#4aa36b',
    shortLabel: 'Cu',
    symbol: 'leaf',
  }),
  buildPlant({
    id: 'zucchini',
    commonName: 'Zucchini',
    scientificName: 'Cucurbita pepo',
    familyId: 'cucurbit',
    cropCategory: 'Fruiting',
    lifecycle: 'annual',
    frostSensitivity: 'tender',
    heatSensitivity: 'moderate',
    supportNeeds: 'none',
    spacingInches: 24,
    rowSpacingInches: 36,
    daysToMaturityMin: 45,
    daysToMaturityMax: 60,
    indoorStartWeeksBeforeLastFrost: 3,
    directSowWeeksRelativeToLastFrost: 1,
    transplantWeeksRelativeToLastFrost: 2,
    transplantMinNightTempF: 55,
    notes: 'Large, fast-growing cucurbit that needs generous spacing and regular harvests.',
    defaultPlanningMethod: 'direct_sow',
    edgeClearanceInches: 6,
    color: '#6ebf55',
    shortLabel: 'Zu',
    symbol: 'leaf',
  }),
  buildPlant({
    id: 'pumpkin',
    commonName: 'Pumpkin',
    scientificName: 'Cucurbita maxima',
    familyId: 'cucurbit',
    cropCategory: 'Fruiting',
    lifecycle: 'annual',
    frostSensitivity: 'tender',
    heatSensitivity: 'moderate',
    supportNeeds: 'none',
    spacingInches: 36,
    rowSpacingInches: 72,
    daysToMaturityMin: 90,
    daysToMaturityMax: 120,
    indoorStartWeeksBeforeLastFrost: 3,
    directSowWeeksRelativeToLastFrost: 2,
    transplantWeeksRelativeToLastFrost: 3,
    transplantMinNightTempF: 55,
    notes: 'Vining crop with large space needs. Often better in dedicated beds or edge zones.',
    defaultPlanningMethod: 'direct_sow',
    edgeClearanceInches: 8,
    color: '#f28b2f',
    shortLabel: 'Pk',
    symbol: 'sun',
  }),
  buildPlant({
    id: 'broccoli',
    commonName: 'Broccoli',
    scientificName: 'Brassica oleracea var. italica',
    familyId: 'brassica',
    cropCategory: 'Flowering',
    lifecycle: 'annual',
    frostSensitivity: 'semi_hardy',
    heatSensitivity: 'high',
    supportNeeds: 'none',
    spacingInches: 18,
    rowSpacingInches: 24,
    daysToMaturityMin: 60,
    daysToMaturityMax: 80,
    indoorStartWeeksBeforeLastFrost: 6,
    directSowWeeksRelativeToLastFrost: 0,
    transplantWeeksRelativeToLastFrost: -2,
    transplantMinNightTempF: 40,
    notes: 'Cool-season brassica that often performs best as a transplant before heat arrives.',
    defaultPlanningMethod: 'indoor_start',
    edgeClearanceInches: 4,
    color: '#3b8f52',
    shortLabel: 'Br',
    symbol: 'clover',
  }),
  buildPlant({
    id: 'cabbage',
    commonName: 'Cabbage',
    scientificName: 'Brassica oleracea var. capitata',
    familyId: 'brassica',
    cropCategory: 'Leafy',
    lifecycle: 'annual',
    frostSensitivity: 'hardy',
    heatSensitivity: 'high',
    supportNeeds: 'none',
    spacingInches: 18,
    rowSpacingInches: 24,
    daysToMaturityMin: 70,
    daysToMaturityMax: 100,
    indoorStartWeeksBeforeLastFrost: 6,
    directSowWeeksRelativeToLastFrost: -2,
    transplantWeeksRelativeToLastFrost: -2,
    transplantMinNightTempF: 40,
    notes: 'Cool-season head crop that handles chilly weather well but suffers in prolonged heat.',
    defaultPlanningMethod: 'indoor_start',
    edgeClearanceInches: 4,
    color: '#6aa86b',
    shortLabel: 'Cb',
    symbol: 'leaf',
  }),
  buildPlant({
    id: 'kale',
    commonName: 'Kale',
    scientificName: 'Brassica oleracea var. sabellica',
    familyId: 'brassica',
    cropCategory: 'Leafy',
    lifecycle: 'biennial',
    frostSensitivity: 'hardy',
    heatSensitivity: 'high',
    supportNeeds: 'none',
    spacingInches: 12,
    rowSpacingInches: 18,
    daysToMaturityMin: 50,
    daysToMaturityMax: 65,
    indoorStartWeeksBeforeLastFrost: 4,
    directSowWeeksRelativeToLastFrost: -4,
    transplantWeeksRelativeToLastFrost: -4,
    transplantMinNightTempF: 35,
    notes: 'Very cold-tolerant leafy crop that can be direct sown or transplanted in cool seasons.',
    defaultPlanningMethod: 'indoor_start',
    edgeClearanceInches: 4,
    color: '#406f46',
    shortLabel: 'Ka',
    symbol: 'leaf',
  }),
  buildPlant({
    id: 'carrot',
    commonName: 'Carrot',
    scientificName: 'Daucus carota subsp. sativus',
    familyId: 'carrot_family',
    cropCategory: 'Root',
    lifecycle: 'biennial',
    frostSensitivity: 'hardy',
    heatSensitivity: 'moderate',
    supportNeeds: 'none',
    spacingInches: 3,
    rowSpacingInches: 12,
    daysToMaturityMin: 60,
    daysToMaturityMax: 80,
    indoorStartWeeksBeforeLastFrost: null,
    directSowWeeksRelativeToLastFrost: -2,
    transplantWeeksRelativeToLastFrost: null,
    transplantMinNightTempF: null,
    notes: 'Best direct sown. Root quality depends on loose soil and even moisture.',
    defaultPlanningMethod: 'direct_sow',
    edgeClearanceInches: 1,
    color: '#ff9f43',
    shortLabel: 'Cr',
    symbol: 'root',
  }),
  buildPlant({
    id: 'radish',
    commonName: 'Radish',
    scientificName: 'Raphanus sativus',
    familyId: 'brassica',
    cropCategory: 'Root',
    lifecycle: 'annual',
    frostSensitivity: 'hardy',
    heatSensitivity: 'high',
    supportNeeds: 'none',
    spacingInches: 2,
    rowSpacingInches: 12,
    daysToMaturityMin: 25,
    daysToMaturityMax: 40,
    indoorStartWeeksBeforeLastFrost: null,
    directSowWeeksRelativeToLastFrost: -4,
    transplantWeeksRelativeToLastFrost: null,
    transplantMinNightTempF: null,
    notes: 'Fast cool-season root crop usually direct sown in short successions.',
    defaultPlanningMethod: 'direct_sow',
    edgeClearanceInches: 1,
    color: '#eb5a69',
    shortLabel: 'Rd',
    symbol: 'root',
  }),
  buildPlant({
    id: 'beet',
    commonName: 'Beet',
    scientificName: 'Beta vulgaris',
    familyId: 'goosefoot',
    cropCategory: 'Root',
    lifecycle: 'biennial',
    frostSensitivity: 'semi_hardy',
    heatSensitivity: 'moderate',
    supportNeeds: 'none',
    spacingInches: 4,
    rowSpacingInches: 12,
    daysToMaturityMin: 50,
    daysToMaturityMax: 70,
    indoorStartWeeksBeforeLastFrost: null,
    directSowWeeksRelativeToLastFrost: -2,
    transplantWeeksRelativeToLastFrost: null,
    transplantMinNightTempF: null,
    notes: 'Direct sown root crop that also provides edible greens.',
    defaultPlanningMethod: 'direct_sow',
    edgeClearanceInches: 2,
    color: '#a64364',
    shortLabel: 'Be',
    symbol: 'root',
  }),
  buildPlant({
    id: 'lettuce',
    commonName: 'Lettuce',
    scientificName: 'Lactuca sativa',
    familyId: 'aster',
    cropCategory: 'Leafy',
    lifecycle: 'annual',
    frostSensitivity: 'semi_hardy',
    heatSensitivity: 'high',
    supportNeeds: 'none',
    spacingInches: 8,
    rowSpacingInches: 12,
    daysToMaturityMin: 45,
    daysToMaturityMax: 65,
    indoorStartWeeksBeforeLastFrost: 4,
    directSowWeeksRelativeToLastFrost: -4,
    transplantWeeksRelativeToLastFrost: -2,
    transplantMinNightTempF: 35,
    notes: 'Cool-season leafy crop that can be transplanted or direct sown in quick successions.',
    defaultPlanningMethod: 'direct_sow',
    edgeClearanceInches: 4,
    color: '#7fbe5e',
    shortLabel: 'Lt',
    symbol: 'leaf',
  }),
  buildPlant({
    id: 'spinach',
    commonName: 'Spinach',
    scientificName: 'Spinacia oleracea',
    familyId: 'goosefoot',
    cropCategory: 'Leafy',
    lifecycle: 'annual',
    frostSensitivity: 'hardy',
    heatSensitivity: 'high',
    supportNeeds: 'none',
    spacingInches: 4,
    rowSpacingInches: 12,
    daysToMaturityMin: 35,
    daysToMaturityMax: 50,
    indoorStartWeeksBeforeLastFrost: null,
    directSowWeeksRelativeToLastFrost: -6,
    transplantWeeksRelativeToLastFrost: null,
    transplantMinNightTempF: null,
    notes: 'Short-season leafy crop that bolts quickly in heat and is usually direct sown.',
    defaultPlanningMethod: 'direct_sow',
    edgeClearanceInches: 2,
    color: '#426e46',
    shortLabel: 'Sp',
    symbol: 'leaf',
  }),
  buildPlant({
    id: 'onion',
    commonName: 'Onion',
    scientificName: 'Allium cepa',
    familyId: 'allium',
    cropCategory: 'Bulb',
    lifecycle: 'biennial',
    frostSensitivity: 'hardy',
    heatSensitivity: 'moderate',
    supportNeeds: 'none',
    spacingInches: 4,
    rowSpacingInches: 12,
    daysToMaturityMin: 90,
    daysToMaturityMax: 120,
    indoorStartWeeksBeforeLastFrost: 10,
    directSowWeeksRelativeToLastFrost: -4,
    transplantWeeksRelativeToLastFrost: -4,
    transplantMinNightTempF: 35,
    notes: 'Often started early as seedlings or sets. Good candidate for long-range schedule planning.',
    defaultPlanningMethod: 'indoor_start',
    edgeClearanceInches: 2,
    color: '#d8c27d',
    shortLabel: 'On',
    symbol: 'diamond',
  }),
  buildPlant({
    id: 'garlic',
    commonName: 'Garlic',
    scientificName: 'Allium sativum',
    familyId: 'allium',
    cropCategory: 'Bulb',
    lifecycle: 'perennial',
    frostSensitivity: 'hardy',
    heatSensitivity: 'low',
    supportNeeds: 'none',
    spacingInches: 6,
    rowSpacingInches: 12,
    daysToMaturityMin: 240,
    daysToMaturityMax: 270,
    indoorStartWeeksBeforeLastFrost: null,
    directSowWeeksRelativeToLastFrost: -20,
    transplantWeeksRelativeToLastFrost: null,
    transplantMinNightTempF: null,
    notes: 'Typically planted in fall from cloves, but still useful to track as a direct-to-bed crop plan.',
    defaultPlanningMethod: 'direct_sow',
    edgeClearanceInches: 3,
    color: '#e1d6b2',
    shortLabel: 'Ga',
    symbol: 'diamond',
  }),
  buildPlant({
    id: 'peas',
    commonName: 'Peas',
    scientificName: 'Pisum sativum',
    familyId: 'legume',
    cropCategory: 'Legume',
    lifecycle: 'annual',
    frostSensitivity: 'hardy',
    heatSensitivity: 'high',
    supportNeeds: 'trellis',
    spacingInches: 3,
    rowSpacingInches: 18,
    daysToMaturityMin: 55,
    daysToMaturityMax: 70,
    indoorStartWeeksBeforeLastFrost: null,
    directSowWeeksRelativeToLastFrost: -6,
    transplantWeeksRelativeToLastFrost: null,
    transplantMinNightTempF: null,
    notes: 'Cool-season legume that is usually direct sown early and appreciates support.',
    defaultPlanningMethod: 'direct_sow',
    edgeClearanceInches: 2,
    color: '#65a561',
    shortLabel: 'Pe',
    symbol: 'clover',
  }),
  buildPlant({
    id: 'beans',
    commonName: 'Beans',
    scientificName: 'Phaseolus vulgaris',
    familyId: 'legume',
    cropCategory: 'Legume',
    lifecycle: 'annual',
    frostSensitivity: 'tender',
    heatSensitivity: 'moderate',
    supportNeeds: 'trellis',
    spacingInches: 4,
    rowSpacingInches: 24,
    daysToMaturityMin: 50,
    daysToMaturityMax: 65,
    indoorStartWeeksBeforeLastFrost: null,
    directSowWeeksRelativeToLastFrost: 1,
    transplantWeeksRelativeToLastFrost: null,
    transplantMinNightTempF: null,
    notes: 'Warm-season legume usually direct sown once soil temperatures have warmed.',
    defaultPlanningMethod: 'direct_sow',
    edgeClearanceInches: 2,
    color: '#6a9f4d',
    shortLabel: 'Bn',
    symbol: 'clover',
  }),
  buildPlant({
    id: 'corn',
    commonName: 'Corn',
    scientificName: 'Zea mays',
    familyId: 'grass',
    cropCategory: 'Grain',
    lifecycle: 'annual',
    frostSensitivity: 'tender',
    heatSensitivity: 'moderate',
    supportNeeds: 'none',
    spacingInches: 10,
    rowSpacingInches: 30,
    daysToMaturityMin: 70,
    daysToMaturityMax: 100,
    indoorStartWeeksBeforeLastFrost: null,
    directSowWeeksRelativeToLastFrost: 2,
    transplantWeeksRelativeToLastFrost: null,
    transplantMinNightTempF: null,
    notes: 'Usually direct sown in blocks for pollination rather than in a single long row.',
    defaultPlanningMethod: 'direct_sow',
    edgeClearanceInches: 4,
    color: '#f0cb4b',
    shortLabel: 'Co',
    symbol: 'sun',
  }),
  buildPlant({
    id: 'basil',
    commonName: 'Basil',
    scientificName: 'Ocimum basilicum',
    familyId: 'mint',
    cropCategory: 'Herb',
    lifecycle: 'annual',
    frostSensitivity: 'tender',
    heatSensitivity: 'moderate',
    supportNeeds: 'none',
    spacingInches: 12,
    rowSpacingInches: 18,
    daysToMaturityMin: 60,
    daysToMaturityMax: 75,
    indoorStartWeeksBeforeLastFrost: 4,
    directSowWeeksRelativeToLastFrost: 2,
    transplantWeeksRelativeToLastFrost: 1,
    transplantMinNightTempF: 55,
    notes: 'Warm-season herb that can be tray started or direct sown after warm weather settles in.',
    defaultPlanningMethod: 'indoor_start',
    edgeClearanceInches: 4,
    color: '#4e9f63',
    shortLabel: 'Bs',
    symbol: 'clover',
  }),
  buildPlant({
    id: 'cilantro',
    commonName: 'Cilantro',
    scientificName: 'Coriandrum sativum',
    familyId: 'carrot_family',
    cropCategory: 'Herb',
    lifecycle: 'annual',
    frostSensitivity: 'semi_hardy',
    heatSensitivity: 'high',
    supportNeeds: 'none',
    spacingInches: 6,
    rowSpacingInches: 12,
    daysToMaturityMin: 45,
    daysToMaturityMax: 60,
    indoorStartWeeksBeforeLastFrost: 4,
    directSowWeeksRelativeToLastFrost: -2,
    transplantWeeksRelativeToLastFrost: 0,
    transplantMinNightTempF: 40,
    notes: 'Fast herb that often does best with repeated direct sowings in cool weather.',
    defaultPlanningMethod: 'direct_sow',
    edgeClearanceInches: 3,
    color: '#5f9d6b',
    shortLabel: 'Ci',
    symbol: 'leaf',
  }),
  buildPlant({
    id: 'dill',
    commonName: 'Dill',
    scientificName: 'Anethum graveolens',
    familyId: 'carrot_family',
    cropCategory: 'Herb',
    lifecycle: 'annual',
    frostSensitivity: 'semi_hardy',
    heatSensitivity: 'high',
    supportNeeds: 'none',
    spacingInches: 8,
    rowSpacingInches: 18,
    daysToMaturityMin: 40,
    daysToMaturityMax: 60,
    indoorStartWeeksBeforeLastFrost: null,
    directSowWeeksRelativeToLastFrost: -2,
    transplantWeeksRelativeToLastFrost: null,
    transplantMinNightTempF: null,
    notes: 'Usually direct sown. Quick herb crop that also supports beneficial insects when allowed to flower.',
    defaultPlanningMethod: 'direct_sow',
    edgeClearanceInches: 3,
    color: '#7cae6b',
    shortLabel: 'Di',
    symbol: 'leaf',
  }),
  buildPlant({
    id: 'marigold',
    commonName: 'Marigold',
    scientificName: 'Tagetes patula',
    familyId: 'aster',
    cropCategory: 'Flower',
    lifecycle: 'annual',
    frostSensitivity: 'tender',
    heatSensitivity: 'moderate',
    supportNeeds: 'none',
    spacingInches: 10,
    rowSpacingInches: 12,
    daysToMaturityMin: 50,
    daysToMaturityMax: 60,
    indoorStartWeeksBeforeLastFrost: 4,
    directSowWeeksRelativeToLastFrost: 1,
    transplantWeeksRelativeToLastFrost: 1,
    transplantMinNightTempF: 50,
    notes: 'Companion flower kept for saved-data compatibility and future beneficial-insect planning.',
    defaultPlanningMethod: 'indoor_start',
    edgeClearanceInches: 4,
    color: '#f2b824',
    shortLabel: 'Mg',
    symbol: 'sun',
  }),
]

export function getPlantById(plantLibrary, plantId) {
  return plantLibrary.find((plant) => plant.id === plantId) ?? null
}

export function getFamilyById(familyLibrary, familyId) {
  return familyLibrary.find((family) => family.id === familyId) ?? null
}

export function buildPlantOption(plant, family = FAMILY_BY_ID[plant.familyId]) {
  return {
    label: `${plant.commonName} · ${plant.cropCategory}${family ? ` · ${family.commonName}` : ''}`,
    value: plant.id,
    commonName: plant.commonName,
    scientificName: plant.scientificName,
    cropCategory: plant.cropCategory,
    familyCommonName: family?.commonName ?? plant.familyCommonName ?? '',
    spacingInches: plant.spacingInches,
    rowSpacingInches: plant.rowSpacingInches,
    daysToMaturityMin: plant.daysToMaturityMin,
    daysToMaturityMax: plant.daysToMaturityMax,
    frostSensitivity: plant.frostSensitivity,
  }
}
